### ISSUE TITLE
Extras won't install on arch

### ISSUE THREAD

**Issue by porkslapchop** [rilian-la-te/vala-panel-extras#10]
Tried to build the extras from the aur there is always some variation of the same error.

` gobject-2.0.vapi:157.37-157.57: error: The type name `GLib.DuplicateFunc' could not be found
		public T dup_data<T> (string key, GLib.DuplicateFunc<T> dup_func);
		                                  ^^^^^^^^^^^^^^^^^^^^^
gobject-2.0.vapi:160.44-160.64: error: The type name `GLib.DuplicateFunc' could not be found
		public T dup_qdata<T> (GLib.Quark quark, GLib.DuplicateFunc<T> dup_func);
		                                         ^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 48 warning(s)
make[2]: *** [lib/CMakeFiles/internal.dir/build.make:95: lib/internal_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:206: lib/CMakeFiles/internal.dir/all] Error 2
make: *** [Makefile:161: all] Error 2 `

**Comment by porkslapchop** [comment]
Nevermind its a duplicate issue.

**Comment by rilian-la-te** [comment]
Closed by duplicate

**Comment by porkslapchop** [comment]
I know this is a huge request but can you tell me how exactly to delete glib.vapi in the pkgbuild? It just won't work

**Comment by rilian-la-te** [comment]
Update from master, this vapi removed
