### ISSUE TITLE
[Lubuntu 17.10] Volume and Battery Indicators Missing

### ISSUE THREAD

**Issue by data4pass** [rilian-la-te/vala-panel-extras#11]
I only have "update-notifier" and "Network" indicators shown in the StatusNotifier applet. Both Volume and Battery Indicators appear if using XEmbed Tray.

"upower" and "volumeicon-alsa" are already installed on my laptop.

Screenshot:
![Screenshot of my current panel](https://user-images.githubusercontent.com/28884686/35502276-7ae55404-0517-11e8-8392-b39caa25514b.png)

Are there any additional dependencies I need to install since I'm running Lubuntu?

**Edit:** 

There are three .desktop files "ALSA Volume Control Applet", "Weather" and "Keyboard Layout Indicator" that are apparently created to /usr/share/applications/ by vala-panel (I'm not sure which one of these three created these shortcuts: vala-panel, xfce4-sntray-plugin, or vala-panel-extras), will update if I found anything.

**Edit 2:** 

Yep, I opened the three .desktop files with my text editor and changed the "TryExec" command with "Exec" instead (my Lubuntu cannot recognize the command if TryExec is used), copied the edited .desktop files to ~/.config/autostart/ then restarted my laptop. The indicators now appear on the panel.

Screenshot:
![Screenshot of updated panel](https://user-images.githubusercontent.com/28884686/35503961-9beab4be-051c-11e8-8a89-3badd831cf2d.png)

However the Battery indicator is still missing.

Thank you for the assistance!

**Comment by rilian-la-te** [comment]
Show me build log of extras. Do you have started volume and battery?

**Comment by data4pass** [comment]
Is CMakeOutput.log file the correct file?
[Here's the CMakeOutput.log of vala-panel-extras](https://github.com/rilian-la-te/vala-panel-extras/files/1673331/CMakeOutput.log)

**Comment by rilian-la-te** [comment]
Can you start vala-panel-extras-battery in terminal?

**Comment by data4pass** [comment]
Yes! The battery indicator appears, thank you.

However, is this how things should be done? Am I supposed to manually put each plugin to autostart?

**Comment by rilian-la-te** [comment]
You do not like it?

**Comment by data4pass** [comment]
Well, it's not about whether I like it or not, it's just that I'm concerned about whether I'm installing this as it is supposed to be installed.

Suppose that you release a new extra in the future, people with similar problem as mine will have to search for each of the extras' names and put them to autostart. The problem though, only _you_ know the individual extra's names. So, a suggestion, maybe you can list each of the names so that it can be launched manually, to help those who may in the future face a similar problem?

**Comment by rilian-la-te** [comment]
Yes, I can))
This is just vala-panel-extras-<this is name a folder i sources>

**Comment by data4pass** [comment]
Very well, thank you again for the assistance.

**Comment by rilian-la-te** [comment]
Sorry, I misinformed you - names of folder may not give to extras' names)

**Comment by data4pass** [comment]
I see... How about the `this.id` in each of the applets' .vala files?

For example, in the battery .vala file (in ~/vala-panel-extras/applets/batt/battery.vala if you cloned the repo to your home directory) I can Ctrl +F for the `this.id` value in which I get `this.id = "vala-panel-extras-battery";` is this `this.id` value a correct representation of the applets' names?

**Comment by rilian-la-te** [comment]
Yes, status notifier item ids can be used to know all extras' names.
