### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/vala-panel-extras#17]
/home/solaraquarion/build/vala-panel-extras-git/src/vala-panel-extras/applets/weather/weather.vala:248.9-248.56: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
        public void dbusmenu_attributes_location_updated()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/solaraquarion/build/vala-panel-extras-git/src/vala-panel-extras/applets/weather/weather.vala:56.47-56.67: error: The name `ForecastType' does not exist in the context of `GWeather'
                info = new GWeather.Info(null,GWeather.ForecastType.LIST);
                                              ^^^^^^^^^^^^^^^^^^^^^
/home/solaraquarion/build/vala-panel-extras-git/src/vala-panel-extras/applets/weather/weather.vala:56.24-56.73: error: 1 extra arguments for `void GWeather.Info.new (GWeather.Location?)'
                info = new GWeather.Info(null,GWeather.ForecastType.LIST);
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 17 warning(s)
make[2]: *** [applets/weather/CMakeFiles/vala-panel-extras-weather.dir/build.make:79: applets/weather/vala-panel-extras-weather_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:664: applets/weather/CMakeFiles/vala-panel-extras-weather.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
==> ERROR: A failure occurred in build().

**Comment by rilian-la-te** [comment]
GWeather version?

**Comment by SolarAquarion** [comment]
It seems that gnome updated on my system

**Comment by rilian-la-te** [comment]
Vala version, GWeather version. Please, write numbers here.

**Comment by SolarAquarion** [comment]
testing/libgweather 3.28.0+2+gd68784b-1 
testing/vala 0.40.0-1

**Comment by rilian-la-te** [comment]
Thanks. Oops, you use testing.
