### ISSUE TITLE
No extras

### ISSUE THREAD

**Issue by ASAPHAANING** [rilian-la-te/vala-panel-extras#7]
Running all the other plugins on a XFCE 16.04 PC I get the following errors for all the plugins:

`Failed to register: Unable to acquire bus name 'org.valapanel.battery'`

I did install the gnome-control-center and make sure power is allowed for instance.

**Comment by rilian-la-te** [comment]
Do you use sntray or snw or indicator plugin?

**Comment by ASAPHAANING** [comment]
Ah shit! I was using XEmbed. Built your xfce/vala sntray and everything is running perfectly! :+1:

Quick question: Is there a way to change Fahrenheit to celcius in weather app?

**Comment by rilian-la-te** [comment]
AFAIK, it is celsius only. Can you post screen with Fahrenheit? And this works not only in sntray, also, in snw, in kde, in various indicator plugins.

**Comment by ASAPHAANING** [comment]
http://storage9.static.itmages.com/i/16/0717/h_1468744943_7707037_08be865ae9.png

Could it be libgweather fetching locale data off my distro that determines wether or not to show fahrenheit? Thanks for writing Vala Panel and its derrivatives, it's really a great panel.

**Comment by rilian-la-te** [comment]
I do not know about this. But extras uses generic gweather settings, so you can change it there. I will close this issue now.  All thanks to lxpanel devs:)

**Comment by ASAPHAANING** [comment]
Just a quick comment to anyone experiencing this issue. Running the command:

`gsettings set org.gnome.GWeather temperature-unit "'centigrade'"`

Will change it from Fahrenheit to Celsius.
