### ISSUE TITLE
Fix the compilation issue 

### ISSUE THREAD

**Issue by Ufeldraku** [rilian-la-te/vala-panel-extras#8]
In the previous report abort GLib.quark, you can't compile properly even if you delete glib-2.0.vapi, yo need these special patches 
> https://build.opensuse.org/package/view_file/home:Newt:Loki/vala-panel-extras/vala-panel-extras-fix-gquarks.patch?expand=1 
> https://build.opensuse.org/package/view_file/home:Newt:Loki/vala-panel-extras/vala-panel-extras-fix-xkb-build.patch?expand=1

**Comment by rilian-la-te** [comment]
Make PR, please:-)

**Comment by Ufeldraku** [comment]
¿PR? What am I going to promote?
Jokes aside, I just report issues, I don't know how to do Pull Requests.

**Comment by Ufeldraku** [comment]
I still need to remove glib-2.0.vapi in order to compile?
When will this be fixed?

**Comment by rilian-la-te** [comment]
If you are compile manually, it will be fixed after bumping Gtk min version

**Comment by Ufeldraku** [comment]
¿? I use the aur's version.

**Comment by rilian-la-te** [comment]
I mean official GTK min version. Now it is 3.12 & vala 0.24. I plan to bump
it to 3.16 + vala 0.28

**Comment by Ufeldraku** [comment]
How much time would that take?

**Comment by rilian-la-te** [comment]
But PKGBUILD now must remove glib-2.0.vapi for you:-)
