### ISSUE TITLE
gtx-appmenu dependencies

### ISSUE THREAD

**Issue by Ufeldraku** [rilian-la-te/vala-panel-extras#9]
The gtk2-appmenu neither gtk3-appmenu dependencies exist.

**Comment by rilian-la-te** [comment]
It reccomnends this packages, but not depends. It is correct.

**Comment by Ufeldraku** [comment]
I tried thunar with your appmenu, however it doesn't work.
So, are you sure that those packages aren't needed?

**Comment by rilian-la-te** [comment]
Without this packages appmenu will works with certain GTK3 apps like file-roller.

**Comment by Ufeldraku** [comment]
Is there any way of getting those packages?

**Comment by rilian-la-te** [comment]
[https://aur.archlinux.org/packages/unity-gtk-module-standalone-bzr/](unity-gtk-module) in AUR
~/.bashrc:
`export GTK_MODULES=GTK_MODULES:unity-gtk-module
export UBUNTU_MENUPROXY = 1`

**Comment by Ufeldraku** [comment]
Won't it break stuff?

**Comment by rilian-la-te** [comment]
No, it is completely revertable.

**Comment by Ufeldraku** [comment]
You nice man, but it will work with stuff like gedit, pluma, etc?

**Comment by rilian-la-te** [comment]
it just install unity tools for appmenu. It will works with all XFCE stuff, with most Gnome stuff (not working with unpatched gnome-terminal and unpatched astleriot), and with Chrome and Qt4 stuff

**Comment by Ufeldraku** [comment]
Ok, works as intended, thanks!
